### ISSUE TITLE
request to add "Humidity_Transport" as an additional entity

### ISSUE THREAD

**Issue by MaxiKingXXL** [nielstron/ha_bayernluefter#12]
Request to add  "Humidity_Transport" as an additional attribute in sensor.py

FROM:
ABS_HUM_MEASURES = [
    "abs_Humidity_In",
    "abs_Humidity_Out"
]

TO:
ABS_HUM_MEASURES = [
    "abs_Humidity_In",
    "abs_Humidity_Out",
    "Humidity_Transport",
]

**Comment by nielstron** [comment]
It may make sense to add humidity transport as an entity. I am wondering - does it make sense to treat it as an "abosolute humidity measure"? Is the unit of humidity transport CONCENTRATION_MILLIGRAMS_PER_CUBIC_METER?

**Comment by MaxiKingXXL** [comment]
The original interface shows CONCENTRATION_**GRAMS**_PER_CUBIC_METER but to be consistent with other values in the HA integration CONCENTRATION_MILLIGRAMS_PER_CUBIC_METER would make sense.

**Comment by nielstron** [comment]
Good point, I changed it to milligrams
