### ISSUE TITLE
Mehrere Bayernlüfter

### ISSUE THREAD

**Issue by dieterxy** [nielstron/ha_bayernluefter#6]
Hallo Nils,
das ist tolle Erweiterung für Homeassistant. Ich habe aber das gleiche Problem wie Fasanenpark: Ich habe mehrere Bayernlüfter.
Vielleicht hast du ja noch mal die Gelegenheit, das Addon für mehrere Lüfter zu enablen. Wäre sehr hilfreich.
Grüße
Dieter

**Comment by nielstron** [comment]
Duplicate of #5

**Comment by nielstron** [comment]
hi @dieterxy 

da es sich um das selbe problem handelt würde ich die diskussion gerne im selben thread führen. siehe #5
